spring:
  application:
    name: @project.name@
  datasource:
    name: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

